config:
  _target_: multivae.models.CVAEConfig
  conditioning_modalities: ['age', 'sex']
  main_modality: pet_linear
  latent_dim: ??
  decoder_dist: normal
  beta: 10.0
  sigma_variation: null
  sparse: False
  log_sigma_init: -2.0
  log_alpha_init: 0.0
  mean_over_batch: False

name: cvae

load_from_folder:
  _target_: multivae.models.AutoModel.load_from_folder

cond_in_encoder:
  use: False
  hidden_dims: [128]
  joint_layers: [128]
  activation: relu

cond_in_decoder:
  use: False
  hidden_dims: [256,32]
  activation: relu

cond_in_prior:
  use: False
  hidden_dims: [256]
  activation: relu
